name: google_oauth2_client
version: 0.4.2
authors:
- Gerwin Sturm <scarygami@gmail.com>
- Adam Singer <financeCoding@gmail.com>
- Kevin Moore <kevmoo@google.com>
description: Library to use for Google OAuth2 authentication / Client-side flow
homepage: https://github.com/dart-gde/dart-google-oauth2-library
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  crypto: any
  http: any
  oauth2: any
  path: any
dev_dependencies:
  browser: any
  hop: any
